SuperLock = Virtual1

Super = Enter | CapsLock

# Tap on hold Enter Enter / Super
Enter{CapsLock} >> SuperLock #### Extended on Tab
Enter{Meta} >> SuperLock #### Extended on Tab
Super{Any} >> Meta{Any}
Super{200ms} >> Meta
# NumPad
Tab{M} >> Numpad1
Tab{Comma} >> Numpad2
Tab{Period} >> Numpad3
Tab{J} >> Numpad4
Tab{K} >> Numpad5
Tab{L} >> Numpad6
Tab{U} >> Numpad7
Tab{I} >> Numpad8
Tab{O} >> Numpad9
Tab{Space} >> Numpad0
Tab{7} >> NumLock
Tab{AltRight} >> NumpadDecimal
Tab{1} >> MediaTrackPrevious
Tab{2} >> MediaPlayPause
Tab{3} >> MediaTrackNext
#Dvorak
A_ = A
B_ = N
C_ = I
D_ = H
E_ = D
F_ = Y
G_ = U
H_ = J
I_ = G
J_ = C
K_ = V
L_ = P
M_ = M
N_ = L
O_ = S
P_ = R
Q_ = X
R_ = O
S_ = Semicolon
T_ = K
U_ = F
V_ = Period
W_ = Comma
X_ = B
Y_ = T
Z_ = Slash
##################################################
[stage]
# Lock Meta
IntlBackslash >> SuperLock
##################################################
[stage]
[modifier = "SuperLock"]
ContextActive >> Meta
#  Unlock
#Escape >>  Escape SuperLock
#Enter >> Enter  SuperLock
Super >> SuperLock
##################################################
[stage]
# propose two keys one of each side of the keyboar
SetBookMark = Meta{Backslash} $0_ >> $(xdotool getactivewindow > /home/max/.bookmarks/$0; notify-send "window $0 bookmarked")
ReadBookMark =  Meta{Q} $0_ >> $(xdotool windowactivate $(cat  ~/.bookmarks/$0))
SetBookMark[A]; ReadBookMark[A]
SetBookMark[B]; ReadBookMark[B]
SetBookMark[C]; ReadBookMark[C]
SetBookMark[D]; ReadBookMark[D]
SetBookMark[E]; ReadBookMark[E]
SetBookMark[F]; ReadBookMark[F]
SetBookMark[G]; ReadBookMark[G]
SetBookMark[H]; ReadBookMark[H]
SetBookMark[I]; ReadBookMark[I]
SetBookMark[J]; ReadBookMark[J]
SetBookMark[K]; ReadBookMark[K]
SetBookMark[L]; ReadBookMark[L]
SetBookMark[M]; ReadBookMark[M]
SetBookMark[N]; ReadBookMark[N]
SetBookMark[O]; ReadBookMark[O]
SetBookMark[P]; ReadBookMark[P]
SetBookMark[Q]; ReadBookMark[Q]
SetBookMark[R]; ReadBookMark[R]
SetBookMark[S]; ReadBookMark[S]
SetBookMark[T]; ReadBookMark[T]
SetBookMark[U]; ReadBookMark[U]
SetBookMark[V]; ReadBookMark[V]
SetBookMark[W]; ReadBookMark[W]
SetBookMark[X]; ReadBookMark[X]
SetBookMark[Y]; ReadBookMark[Y]
SetBookMark[Z]; ReadBookMark[Z]
ReadBookMark[A]; ReadBookMark[A]
ReadBookMark[B]; ReadBookMark[B]
ReadBookMark[C]; ReadBookMark[C]
ReadBookMark[D]; ReadBookMark[D]
ReadBookMark[E]; ReadBookMark[E]
ReadBookMark[F]; ReadBookMark[F]
ReadBookMark[G]; ReadBookMark[G]
ReadBookMark[H]; ReadBookMark[H]
ReadBookMark[I]; ReadBookMark[I]
ReadBookMark[J]; ReadBookMark[J]
ReadBookMark[K]; ReadBookMark[K]
ReadBookMark[L]; ReadBookMark[L]
ReadBookMark[M]; ReadBookMark[M]
ReadBookMark[N]; ReadBookMark[N]
ReadBookMark[O]; ReadBookMark[O]
ReadBookMark[P]; ReadBookMark[P]
ReadBookMark[Q]; ReadBookMark[Q]
ReadBookMark[R]; ReadBookMark[R]
ReadBookMark[S]; ReadBookMark[S]
ReadBookMark[T]; ReadBookMark[T]
ReadBookMark[U]; ReadBookMark[U]
ReadBookMark[V]; ReadBookMark[V]
ReadBookMark[W]; ReadBookMark[W]
ReadBookMark[X]; ReadBookMark[X]
ReadBookMark[Y]; ReadBookMark[Y]
ReadBookMark[Z]; ReadBookMark[Z]

##================== Apps
Meta{A_} T_ >> $(gnome-terminal)
Meta{A_} Shift{T_} >> $(gnome-terminal --profile=Black)
Tmux = Meta{A_} $0 >> $(gnome-terminal -- tmux new -A -s$0) ; Meta{A_} Shift{$0} >> $(gnome-terminal --profile=Black -- tmux new -A -s$0)
Tmux[1]
Tmux[2]
Tmux[3]
Tmux[4]
Tmux[5]
Tmux[6]
Tmux[7]
Tmux[8]
Tmux[9]
Meta{A_} S_ >> $(spotify)
Meta{A_} F_ >> $(qutebrowser)
Meta{A_} Shift{F_} >> $(firefox)
Meta{A_} L_ >> $(libreoffice --calc)
