SuperLock = Virtual1

Super = Enter | CapsLock

# Tap on hold Enter Enter / Super
Super{200ms} >> Meta
Super{Any} >> Meta{Any}

#### Extended on Tab
# NumPad
Tab{M} >> Numpad1
Tab{Comma} >> Numpad2
Tab{Period} >> Numpad3
Tab{J} >> Numpad4
Tab{K} >> Numpad5
Tab{L} >> Numpad6
Tab{U} >> Numpad7
Tab{I} >> Numpad8
Tab{O} >> Numpad9
Tab{Space} >> Numpad0
Tab{7} >> NumLock
Tab{AltRight} >> NumpadDecimal
Tab{1} >> MediaTrackPrevious
Tab{2} >> MediaPlayPause
Tab{3} >> MediaTrackNext

